#!/usr/bin/env bash
set -euo pipefail

ZSH_VI_MODE_DIR="$HOME/dippindots/.zsh-vi-mode"

if [[ ! -d "$ZSH_VI_MODE_DIR/.git" ]]; then
  git clone https://github.com/jeffreytse/zsh-vi-mode "$ZSH_VI_MODE_DIR"
else
  git -C "$ZSH_VI_MODE_DIR" pull --ff-only --quiet
fi

echo "Done."
echo "Make sure your ~/.zshrc has:"
echo "source $ZSH_VI_MODE_DIR/zsh-vi-mode.plugin.zsh"

source $ZSH_VI_MODE_DIR/zsh-vi-mode.plugin.zsh
